version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    commit-message:
      prefix: "[Dependabot]"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[Dependabot]"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
